### ISSUE TITLE
JP Server not working on Huawei P Smart

### ISSUE THREAD

**Issue by IazIow** [MathewSachin/Fate-Grand-Automata#313] opened 2020-08-28 03:20 UTC
**Describe the bug**
As much as the app functions well on NA, it doesn't react on any screens on JP. I had this same issue with the .lua code, but it could be fixed by going in the "scale" script by adding a line, [here.](https://cdn.discordapp.com/attachments/613346172429402122/748742463815942274/unknown.png)

**Screenshots**
[The settings.](https://cdn.discordapp.com/attachments/613346172429402122/748743034572636200/Screenshot_20200828_051110_com.mathewsachin.fategrandautomata.jpg)
[The Skills/pref
](https://cdn.discordapp.com/attachments/613346172429402122/748743034866368562/Screenshot_20200828_051123_com.mathewsachin.fategrandautomata.jpg)

**Video**
[The script not starting.](https://streamable.com/60041n)
[Debug mode.](https://streamable.com/olao0j)
Same on every screens.

**Device Info:**
- Device model: Huawei P Smart
- Screen size: 1080x2340
- Android: 9
- RAM: 3Gb

**Comment by tchofy** [comment] 2020-08-28 03:32
Seems like a duplicate of #259. [You could try the instructions on this post and see if it helps](https://github.com/MathewSachin/Fate-Grand-Automata/issues/259#issuecomment-674444429), but like you mentioned, it might be caused by screen scaling.

**Comment by MathewSachin** [comment] 2020-08-28 03:40
@tchofy I think it's similar to #269.
FGO isn't running full-screen and isn't centred on the screen.
That's why the script isn't detecting it and doing anything.

Go to `Settings > Display & brightness > More display settings > Full-Screen Display` on your phone and turn it ON for FGO.
I think this should work. If it doesn't, post a screenshot of how FGO looks after turning this ON.

**Comment by IazIow** [comment] 2020-08-28 07:43
@MathewSachin did just that and it worked great, thanks!

**Closed** 2020-08-28 07:45 UTC
Labels: bug
