### ISSUE TITLE
Quest closeouts fail with bond level up screen

### ISSUE THREAD

**Issue by Mysty-chan** [MathewSachin/Fate-Grand-Automata#70] opened 2020-04-25 15:27 UTC
> MAKE SURE YOU TESTED THE LATEST RELEASE.

> See 'SAMSUNG.md' first, if you're a Samsung user.

**Describe the bug**
Game takes too long to load the bond level up screen(s) after battle completion, so the rapid taps for clearing the various pop-ups begin too early and miss clearing the material drops to fully exit the quest. Then the app just sits there waiting for manual clearing the screen before resuming the script with the next battle.

**Comment by MathewSachin** [comment] 2020-04-25 15:30
@Mysty-chan, I can close #61 and #53, right?

Also, I'm copying my Gamepress response here for reference.

> That Bond level up issue happened for me too. It probably has to do only with timing.
>
>Currently, the script clicks around 55 times when it detects the result screen with each click having a duration of 50ms and there is an interval of 10ms between the clicks.
>
>We can tweak these parameters, but, there can be cases where all servants Bond up at the same time. The amount of clicks required to handle such a case would be too much for the case when no servants Bond up. I think we need to do more image matching here instead of blinding clicking repeatedly.

**Comment by reconman** [comment] 2020-04-25 15:38
I checked the code and it should treat the Master EXP and Bond screen the same way:

https://github.com/MathewSachin/Fate-Grand-Automata/blob/d3e3ae56e84f040f4837414af77ce6173bf509d7/FateGrandAutomata.Core/AutoBattle.cs#L134-L147

So if ![](https://github.com/MathewSachin/Fate-Grand-Automata/blob/master/FateGrandAutomata.Core/images/En/bond.png?raw=true) is visible, it will also click 55 times.

That's why I requested a screenshot.

**Comment by MathewSachin** [comment] 2020-04-25 15:46
I'm guessing the problem is that the 55 clicks might be ending around the battle reward screens which are not checked by the script IIRC.

**Comment by reconman** [comment] 2020-04-25 15:53
You're completely right, both "bond.png" and "result.png" belong to the bond point screen. If the app got past that, nothing happens anymore.

**Comment by reconman** [comment] 2020-04-25 15:57
JP screenshots:
![image](https://user-images.githubusercontent.com/12360257/80284329-281d5100-871e-11ea-8fe6-17ae7bec6cd1.png)
![image](https://user-images.githubusercontent.com/12360257/80284295-f73d1c00-871d-11ea-8663-864b6af4e436.png)

I can produce some NA ones after the raid quests start again.

**Comment by Mysty-chan** [comment] 2020-04-25 17:49
#53, certainly. #61... It's better with the reduced sensitivity to swipe, but it is still a bit difficult to get a successful click when I'm in a hurry to stop the script for whatever reason.

I can try for a pic after raids resume

**Comment by reconman** [comment] 2020-04-25 19:38
Fixed with d1748279a6f2a112ae04d72b39b4312d45de04b8

I was able to reproduce it. The bond icon region only fit JP, not NA.

The next release is currently building.

**Closed by reconman** 2020-04-25 19:38 UTC
Labels: bug

**Comment by MathewSachin** [comment] 2020-04-26 06:29
We need to do better here. My Ecchan leveled up (3SQ yay!), but the script stopped clicking on the event point reward screen.
