### ISSUE TITLE
Script keeps breaking up, but is not consistent. Is the a log or something?

### ISSUE THREAD

**Issue by runelt99** [MathewSachin/Fate-Grand-Automata#468] opened 2020-09-24 12:49 UTC
**Before opening an issue:
- [x] I tested the latest release**
Yes, i checked google play and see no new update.
**- [ ] I looked at other issues (even the closed ones)**
Yes
**- [ ] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)**
Yes
**- [ ] I'll fill this template properly**
Ok
**> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.**

**Describe the bug**
After running for a longer time, script breaks, when i check phone it is usually looking at servant stats on turn 3. I know the script is not at fault because i know that it can successfully 3t the node, its just that after some unknown amount of time i return with a broken script.

I am running gilfest's ticket node with 1t para, 2t arash and 3t spartacus. On 2nd turn arash is suppost to use his np to let shekspere on for spartacus to get all oh his np, however whenever it breaks it always ends up with it looking at first servant's stats - i realise that he was maybe trying to activate spartacus's skills but somehow clicks on servant? For some reason arash is still alive and im left to manually clean up the wave...

For screenshot i can try letting it grind for a while more to get it again, but for video the length would be too big to be reasonable since most time is spent normally grinding.

**Device Info (please fill at-least 'Device model'):**
 - Device model: FIG-LX1
 - Screen size: [e.g. 1280x720]
 - Android Version: [e.g. Android 7.1]
 - RAM: 3GB

**Comment by RazorsEdge88** [comment] 2020-09-24 13:24
Duplicate of #462

**Comment by runelt99** [comment] 2020-09-24 13:32
The problem is that I am using a 3t farm. I noticed waver doesn't use 3rd skill too..
Managed around 1k tickets before it broke down.

![Screenshot_20200924_162349_com aniplex fategrandorder en](https://user-images.githubusercontent.com/48949150/94151779-7a0c0380-fe83-11ea-9830-4ce5a9fc20f0.jpg)
![Screenshot_20200924_162359_com aniplex fategrandorder en](https://user-images.githubusercontent.com/48949150/94151786-7b3d3080-fe83-11ea-97f4-93ad15b5d8cb.jpg)

**Comment by MathewSachin** [comment] 2020-09-24 13:36
If you're 3T farming and it gets stuck in any details screen pretty much means that your device lagged when the script clicked on the Attack button I guess.
Have you changed anything in Fine-tune settings? Maybe increase the Wait before turn setting.

**Comment by runelt99** [comment] 2020-09-24 13:40
I specifically returned to defaults after first few breaks. Guess will increase waiting time...

**Comment by runelt99** [comment] 2020-09-25 07:35
Is it possible to have an alarm of some kind when script stops? Even if i can't fix it via making waiting times 4x of normal, i'd like to at least be aware when i need to reset it...

**Comment by RazorsEdge88** [comment] 2020-09-25 11:25
@runelt99 is setted by default that you get a pop-up+notificacion when the script stop by any reason

**Comment by runelt99** [comment] 2020-09-25 17:22
Welp i use muted mode anyway. But i was able to fix it by : doubling skill timer, click and some multiplier.

**Comment by runelt99** [comment] 2020-09-25 19:20
Sorry for opening this, but i don't think its worth it to open new issue. Just got 2 of my servants to bond 10 and it broke the script. Yeah its not common, but still irritating how it barely got into grinding while i was sleeping and turned off.

**Comment by reconman** [comment] 2020-09-25 22:22
That last comment is addressed in #423

**Closed by reconman** 2020-09-25 22:22 UTC
Labels: bug
