### ISSUE TITLE
Is there any way to export my Auto Skills configuration between devices?

### ISSUE THREAD

**Issue by duradara** [MathewSachin/Fate-Grand-Automata#175] opened 2020-07-15 21:20 UTC
Its not really a big problem but I will like to know if there is a way to do it or if there are some plans to add this feature in the future.  
Sorry if my english is bad.

**Comment by reconman** [comment] 2020-07-15 21:22
Duplicate of #165

**Closed by reconman** 2020-07-15 21:22 UTC
Labels: question
