### ISSUE TITLE
FGA doesn't do anything on Motorola G9 Plus 

### ISSUE THREAD

**Issue by Makabra** [MathewSachin/Fate-Grand-Automata#612] opened 2020-12-17 05:43 UTC
Hello, it's something similar of the Nokia 8.1 Issue, nothing happens in support selection or in battle and I tried tweaking everything, notch ON, notch OFF from FGO and FGA. When **I finish** the battle, the refill selection happen but nothing more. The app works in my motorola G6 Play but not in this new cellphone. The server is JP and I tested the canary version but still persists the problem.

**Screenshots**
![Screenshot_20201216-212933](https://user-images.githubusercontent.com/7323474/102448264-9e8cfd00-3fe6-11eb-8ee1-f48720bfc687.png)
![Screenshot_20201216-212941](https://user-images.githubusercontent.com/7323474/102448330-bf555280-3fe6-11eb-9cce-97eaa0349d87.png)

**Video**
https://youtu.be/5t2IQgvRbSU

 - Device model: Motorola G9 Plus
 - Screen size: 2400x1080
 - Android Version: Android 10
 - RAM: 4GB

**Comment by reconman** [comment] 2020-12-17 06:37
Duplicate of #571

**Closed by reconman** 2020-12-17 06:37 UTC
Labels: bug
