### ISSUE TITLE
Add option for "Update Support" looping as a fallback

### ISSUE THREAD

**Issue by duskly** [MathewSachin/Fate-Grand-Automata#460] opened 2020-09-23 08:07 UTC
I'm not sure if this is already a thing, but I didn't notice it in the app. Basically, it would be nice to have a loop update until the app finds the preferred support, if it can't already find a preferred support in the support list.

**Comment by reconman** [comment] 2020-09-23 10:32
Duplicate of #371

**Closed by reconman** 2020-09-23 10:32 UTC
Labels: enhancement
