### ISSUE TITLE
Support Skill level check

### ISSUE THREAD

**Issue by andreavale98** [MathewSachin/Fate-Grand-Automata#172] opened 2020-07-14 08:59 UTC
Since skadi has been released a few days ago in NA, a lot of people put skadi on the caster slot support even without her skill maxed, is there any way to make a Skill Check for the support servant?

**Comment by MathewSachin** [comment] 2020-07-14 09:03
Duplicate of #102 
We're working on it. It's a bit tricky to get right.

**Closed by MathewSachin** 2020-07-14 09:03 UTC
Labels: duplicate
