### ISSUE TITLE
Selecting supports with maxed skills only

### ISSUE THREAD

**Issue by IazIow** [MathewSachin/Fate-Grand-Automata#312] opened 2020-08-28 01:21 UTC
Hey I already put this request on the of lua but I recently found this app so I'll try my luck here!
With the recent rise of Skadi in NA and Castoria in JP, most loopable comps require them with their skills maxed.
It would be pretty neat if we could choose to select certain servants 10/10/10 only.
Like it's done with the CEs maybe?

**Comment by MathewSachin** [comment] 2020-08-28 01:26
Did you try the app before opening a new issue?
This feature is already available.

Duplicate of #102

**Closed by MathewSachin** 2020-08-28 01:26 UTC
Labels: enhancement

**Comment by tchofy** [comment] 2020-08-28 01:29
Got ninja'd.
In case you have trouble finding it, go to Auto Skill > Skill Levels > Preffered Servants > Select the servants you want (probably Skadi, I guess) > Now the option to select Skill Levels will show up, click it and tick the skills you want to have maxed.

**Comment by tchofy** [comment] 2020-08-28 01:31
Also, @MathewSachin, maybe it's a good idea to have the Skill Levels option greyed out instead of hidden if the player hasn't selected a preffered support? Could help with cases like this, but considering that's the first time I'm seeing this issue it might not be worth the effort.

**Comment by MathewSachin** [comment] 2020-08-28 01:35
I think hiding is better to save space. There are too many options in Support selection to show all at once right now.

This is one of the copy-paste issues from FGO- lua. Has happened before too 😂
The person who opened this kind of issue last time hadn't even tried using the app.

**Comment by IazIow** [comment] 2020-08-28 01:50
Ah wheeze you got me there, I thought this app was the same as Fgo Lua, just without the Lua app needed, glad to see that it has way more features. Before posting this I only used it to face card,didn't dive into the support prefs

@MathewSachin thanks man

**Comment by MathewSachin** [comment] 2020-08-28 01:52
It was the same as FGO Lua like 4 months before.
Now, we have many of the pending feature requests in FGO lua implemented here.
It's just easier to get things done in Android/Kotlin than in the Lua script.

**Comment by IazIow** [comment] 2020-08-28 02:04
Nice indeed! However, I just noticed that the script seems unresponsive for JP. 
I had the same issue in the .lua and to fix it, I had to change values in the scaling part of the script to fit the pixel of my screens. (from 0 to 150)
I set my region to JP in the parameters too.

**Comment by MathewSachin** [comment] 2020-08-28 02:07
Hey, can you open a new issue for that?
Let's keep issues clean.

Also, fill out the information asked in the bug template properly or you'll receive the dreaded badge of shame: `insufficient info` label. 🤣
