### ISSUE TITLE
Using MC skills still skips any subsequent actions.

### ISSUE THREAD

**Issue by consistentescape** [MathewSachin/Fate-Grand-Automata#75] opened 2020-04-26 07:07 UTC
> MAKE SURE YOU TESTED THE LATEST RELEASE.

> See 'SAMSUNG.md' first, if you're a Samsung user.

**Describe the bug**
I just did a couple of runs with the new v11.4 update and the problem still exists for me. Also it's not just limited to the Order Change for me, using any MC skill causes a delay big enough that any subsequent actions get clicked even before the animations are completely over. Could you create an optional apk with increased wait times by 5-10 seconds for all MC skills? I think that should fix it for me.

**Screenshots**
Dunno if screenshot is required for this. 

**Device Info (please fill atleast 'Device model'):**
 - Device model: [Samsung A9 Pro]
 - Screen size: [1920x1080]
 - Android Version: [Android 8.0.0]
 - RAM: [4 GB]

**Comment by MathewSachin** [comment] 2020-04-26 07:25
Can you post a video of the script doing order change on your phone? I need to exactly where the lag is.
Preferably, take the video of your screen using another phone/camera so that your phone doesn't lag even more due to the recording.

**Comment by consistentescape** [comment] 2020-04-26 07:50
https://imgur.com/gallery/UyhGLBy

Here's the relevant part of the autoskill I am using. 
x31**e**hidj**g**5
e is the filler skill to account for the delay after order change and it got skipped, g is to account for the delay after I use the MC atk up and it gets clicked some times and some times it doesn't.

**Comment by MathewSachin** [comment] 2020-04-26 08:14
Give me some time to analyze the video.

From what I can see, I think the problem is related to the time the `Attack` button needs to disappear before reappearing on your phone.

**Comment by reconman** [comment] 2020-04-26 08:20
I agree with MathewSachin. So we should probably add some wait time after clicking on the master skill:

https://github.com/MathewSachin/Fate-Grand-Automata/blob/61f7d0871fd27e2d2582cac09bbf6c7e4b249c85/FateGrandAutomata.Core/Modules/AutoSkill.cs#L88-L92

**Comment by reconman** [comment] 2020-04-26 08:34
Correction: To both fix order change and normal master skills, I would propose adding waitVanish here instead of a simple wait. Then increase the waitVanish by a few seconds.

**Comment by MathewSachin** [comment] 2020-04-26 14:43
There is another complication here, we don't always need to wait right after the skill is clicked.
If it is a targetable skill, we have to start the long wait only after target is selected.

The effects of this can be seen right now in targetable skills from how the code is written. The script always waits for at least 2s before clicking on skill target. This is because the `Attack` button doesn't completely disappear when the skill target selection dialog opens.

**Comment by MathewSachin** [comment] 2020-04-26 14:54
An idea I'm getting is we need to add a wait to let the order change dialog close first.
@consistentescape I'll do something for the other master skills too, but first, can you test if this build works for order change: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/88303393

Download the apk from that link, it will be in a zipped folder.

**Comment by consistentescape** [comment] 2020-04-26 15:21
I just did some runs and none of them had any problems with the order change so it seems to be working fine. Thanks for the update, I can wait for the other fixes no problem.

**Comment by MathewSachin** [comment] 2020-04-26 15:55
That great! The video you provided really helped find the cause.

Now, only if I could get a video of other master skills misbehaving, it'd be easier for me to fix. I can't really reproduce this problem on my phone.

**Comment by reconman** [comment] 2020-04-26 16:08
@MathewSachin there is another one in the video, the attack buff. It also misbehaves.

**Comment by MathewSachin** [comment] 2020-04-26 16:10
@reconman The mystic code attack buff seemed fine. Did some skill miss there?

**Comment by reconman** [comment] 2020-04-26 16:12
Ah sorry, must have been an imagination.

**Comment by consistentescape** [comment] 2020-04-26 16:16
The mystic code atk buff only misses sometimes, probably because the animation times are not always the same. But yeah it didn't miss in the video I uploaded.

**Comment by MathewSachin** [comment] 2020-07-22 08:49
@consistentescape The game should be working more smoothly after the engine update and we have configurable delays in `More options / Fine-tune` in the latest release.
So, I'm closing this issue now. Reopen if you still face this problem.

> The animations usually lag up when the skill name is displayed and the other skills get pressed then.

Also, the script might not be able to work properly if the game itself lags too much on your device.

**Closed by MathewSachin** 2020-07-22 08:49 UTC
Labels: bug
