### ISSUE TITLE
Bot doesn't see the designated friend support the first time support selection opens

### ISSUE THREAD

**Issue by Tom3kk** [MathewSachin/Fate-Grand-Automata#265] opened 2020-08-15 20:18 UTC
I've got my bot set up to pick a servant from a specific friend, when it gets to pick it, it immediately shows me the message that the support list will be refreshed in 3 seconds, refreshes and picks the servant - even if he was already there.
[Video of it happening!](https://youtu.be/MQucvgTnJfI)

**Comment by reconman** [comment] 2020-08-15 20:22
Already fixed in #231, will be part of the next release.

Also please don't delete the bug template, you should keep the structure and replace the placeholders.

**Comment by reconman** [comment] 2020-08-15 20:23
Duplicate of #164 and #229

**Closed by reconman** 2020-08-15 20:22 UTC
Labels: bug

**Comment by MathewSachin** [comment] 2020-08-15 20:25
yup, that's what it is. FGA is not waiting long enough for support screen to load completely. Like reconman said, next release shouldn't have this problem.
