### ISSUE TITLE
How to use Refill function without setting the number of repetitions

### ISSUE THREAD

**Issue by GleipnirFR** [MathewSachin/Fate-Grand-Automata#403] opened 2020-09-15 10:53 UTC
Hello,

I'm an old user of the LUA app, and I've started to use yours recently (thanks a lot for this, by the way).
Like the title says : can we use the Refill function in "unlimited" mode ? If my memories are correct, in the LUA app, you could leave the number of repetitions to 0 and the script would use all your apples (or the type you had selected) until depleted.
Right now, if I try to leave the repetitions to 0, the app just exit with the "empty AP" notification. I started the script with no ap left. 

(BTW, I think I might have crashed the app by setting the amount of repetitions to an absurd amount like 9999999 : the app closed, with no way to reopen it without deleting its data. As a fellow developer, I'm sorry to have played the "stupid user" use case :p)

**Comment by MathewSachin** [comment] 2020-09-15 10:57
Duplicate of #400

How many apples could you possibly have? 500-1000. I can't change 0 to use infinite now anyway, since that would be even more complaints.
Just set it to something less than INT_MAX. The latest version on PlayStore won't crash on this either.

> with no way to reopen it without deleting its data.

that depends on the phone. On my phone, the app launched back even after a crash. Xiaomi, Samsung and Huawei play bad in such cases.

**Closed by MathewSachin** 2020-09-15 10:57 UTC
Labels: question
